// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LondonBike {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DistanceView")]
	public partial class DistanceView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_DistanceLabel;
		
		private MonoTouch.UIKit.UIButton __mt_DismissButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DistanceLabel")]
		private MonoTouch.UIKit.UILabel DistanceLabel {
			get {
				this.__mt_DistanceLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("DistanceLabel")));
				return this.__mt_DistanceLabel;
			}
			set {
				this.__mt_DistanceLabel = value;
				this.SetNativeField("DistanceLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DismissButton")]
		private MonoTouch.UIKit.UIButton DismissButton {
			get {
				this.__mt_DismissButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("DismissButton")));
				return this.__mt_DismissButton;
			}
			set {
				this.__mt_DismissButton = value;
				this.SetNativeField("DismissButton", value);
			}
		}
	}
}
