// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LondonBike {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("TimerViewController")]
	public partial class TimerViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_CostLabel;
		
		private MonoTouch.UIKit.UILabel __mt_ElapsedLabel;
		
		private MonoTouch.UIKit.UILabel __mt_PriceIncreaseLabel;
		
		private MonoTouch.UIKit.UIButton __mt_StartButton;
		
		private MonoTouch.UIKit.UILabel __mt_StartedLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CostLabel")]
		private MonoTouch.UIKit.UILabel CostLabel {
			get {
				this.__mt_CostLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("CostLabel")));
				return this.__mt_CostLabel;
			}
			set {
				this.__mt_CostLabel = value;
				this.SetNativeField("CostLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ElapsedLabel")]
		private MonoTouch.UIKit.UILabel ElapsedLabel {
			get {
				this.__mt_ElapsedLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("ElapsedLabel")));
				return this.__mt_ElapsedLabel;
			}
			set {
				this.__mt_ElapsedLabel = value;
				this.SetNativeField("ElapsedLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("PriceIncreaseLabel")]
		private MonoTouch.UIKit.UILabel PriceIncreaseLabel {
			get {
				this.__mt_PriceIncreaseLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("PriceIncreaseLabel")));
				return this.__mt_PriceIncreaseLabel;
			}
			set {
				this.__mt_PriceIncreaseLabel = value;
				this.SetNativeField("PriceIncreaseLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("StartButton")]
		private MonoTouch.UIKit.UIButton StartButton {
			get {
				this.__mt_StartButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("StartButton")));
				return this.__mt_StartButton;
			}
			set {
				this.__mt_StartButton = value;
				this.SetNativeField("StartButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("StartedLabel")]
		private MonoTouch.UIKit.UILabel StartedLabel {
			get {
				this.__mt_StartedLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("StartedLabel")));
				return this.__mt_StartedLabel;
			}
			set {
				this.__mt_StartedLabel = value;
				this.SetNativeField("StartedLabel", value);
			}
		}
	}
}
